name = "KryburyCompress"
uuid = "665f56ad-f4f7-4f50-adde-d55c796959f8"
authors = ["andrew-saydjari <saydjari@g.harvard.edu> and contributors"]
version = "0.1.0"

[deps]
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LowRankOps = "0ea32739-31af-43e6-82ee-ebe6dcf00a6f"

[compat]
FITSIO = "0.17"
KrylovKit = "0.6"
LowRankOps = "0.1"
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
